Repository buildpacks/profile, pull requests merged in 2022-08, with the labels that each got.

#11 Add profile buildpack detect and build logic
  buildpack.toml
  profile/build.go
  profile/build_test.go
  profile/constants.go
  profile/detect.go
  profile/detect_test.go
  scripts/profiled-wrapper.sh
Labels: type:enhancement, semver:major

#14 Streamline test setup
  profile/build_test.go
  profile/detect_test.go
Labels: type:task, semver:patch

#13 Bump pipeline from 1.21.4 to 1.25.2
  .github/pipeline-version
  .github/workflows/pb-create-package.yml
  .github/workflows/pb-minimal-labels.yml
  .github/workflows/pb-synchronize-labels.yml
  .github/workflows/pb-tests.yml
  .github/workflows/pb-update-draft-release.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-pipeline.yml
Labels: type:task, semver:patch

#19 Change GHA user
  .github/pipeline-descriptor.yml
  .github/workflows/pb-create-package.yml
  .github/workflows/pb-synchronize-labels.yml
  .github/workflows/pb-update-draft-release.yml
  .github/workflows/pb-update-go.yml
  .github/workflows/pb-update-pipeline.yml
Labels: type:task, semver:patch

#22 Update README.md
  README.md
Labels: type:documentation, semver:patch

#23 Use the IMPLEMENTATION_GITHUB_TOKEN for the Registry
  .github/pipeline-descriptor.yml
  .github/workflows/pb-create-package.yml
Labels: type:bug, semver:patch
